<?php

namespace AppBundle\Repository;

/**
 * CheckIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckIpRepository extends \Doctrine\ORM\EntityRepository
{
}
