<?php

namespace AppBundle\Repository;

/**
 * UserRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepositoryRepository extends \Doctrine\ORM\EntityRepository
{
}
