app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path:     /register/
    defaults: { _controller: AppBundle:Registration:register }
    
login_check:
    path:     /login_check/
    defaults: { _controller: AppBundle:Registration:register }

category_list:
    path:     /category/list/
    defaults: { _controller: AppBundle:ManageCategory:list }
    
category_create:
    path:     /category/create/
    defaults: { _controller: AppBundle:ManageCategory:create}
    
category_edit: 
    path:     /category/edit/{categoryid}
    defaults: { _controller: AppBundle:ManageCategory:edit }  

category_delete: 
    path:     /category/delete/{categoryid}
    defaults: { _controller: AppBundle:ManageCategory:delete }

survey_list:
    path:     /survey/list/{categoryid}
    defaults: { _controller: AppBundle:ManageSurvey:show }

survey_create: 
    path:     /survey/create/{categoryid}
    defaults: { _controller: AppBundle:ManageSurvey:create }
    
survey_edit: 
    path:     /survey/edit/{surveyid}
    defaults: { _controller: AppBundle:ManageSurvey:edit }  
    
survey_delete: 
    path:     /survey/delete/{surveyid}
    defaults: { _controller: AppBundle:ManageSurvey:delete }
   
question_list:
    path:     /question/list/{surveyid}
    defaults: { _controller: AppBundle:ManageQuestion:list }

question_create: 
    path:     /question/create/{surveyid}
    defaults: { _controller: AppBundle:ManageQuestion:create }

question_edit: 
    path:     /question/edit/{questionid}
    defaults: { _controller: AppBundle:ManageQuestion:edit }  

question_edit_option:
    path:     /question/edit_option/{questionid}
    defaults: { _controller: AppBundle:ManageQuestion:editOption } 
    
question_delete: 
    path:     /question/delete/{questionid}
    defaults: { _controller: AppBundle:ManageQuestion:delete }