app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path:     /register/
    defaults: { _controller: AppBundle:Registration:register }
    
login_check:
    path:     /login_check/
    defaults: { _controller: AppBundle:Registration:register }

survey_list:
    path:     /survey/list/{categoryid}
    defaults: { _controller: AppBundle:ManageSurvey:show }

survey_create: 
    path:     /survey/create/{categoryid}
    defaults: { _controller: AppBundle:ManageSurvey:create }
    
survey_delete: 
    path:     /survey/delete/{surveyid}
    defaults: { _controller: AppBundle:ManageSurvey:delete }
    
survey_edit: 
    path:     /survey/edit/{surveyid}
    defaults: { _controller: AppBundle:ManageSurvey:edit }   
   
category_list:
    path:     /category/list/
    defaults: { _controller: AppBundle:ManageCategory:list }
    
category_create:
    path:     /category/create/
    defaults: { _controller: AppBundle:ManageCategory:create}
    
category_edit: 
    path:     /category/edit/{categoryid}
    defaults: { _controller: AppBundle:ManageCategory:edit }  

category_delete: 
    path:     /category/delete/{categoryid}
    defaults: { _controller: AppBundle:ManageCategory:delete }