app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path:     /register/
    defaults: { _controller: AppBundle:Registration:register }
    
login:
    path:     /login/
    defaults: { _controller: AppBundle:Login:login}

logout:
    path:     /logout/
    defaults: { _controller: AppBundle:Login:logout}

category_list:
    path:     /category/list/
    defaults: { _controller: AppBundle:ManageCategory:list }
    
category_create:
    path:     /category/create/
    defaults: { _controller: AppBundle:ManageCategory:create}
    
category_edit: 
    path:     /category/edit/{categoryid}
    defaults: { _controller: AppBundle:ManageCategory:edit }  

category_delete: 
    path:     /category/delete/{categoryid}
    defaults: { _controller: AppBundle:ManageCategory:delete }

survey_list:
    path:     /survey/list/{categoryid}
    defaults: { _controller: AppBundle:ManageSurvey:show}

survey_create: 
    path:     /survey/create/{categoryid}
    defaults: { _controller: AppBundle:ManageSurvey:create}
    
survey_edit: 
    path:     /survey/edit/{surveyid}
    defaults: { _controller: AppBundle:ManageSurvey:edit}  
    
survey_delete: 
    path:     /survey/delete/{surveyid}
    defaults: { _controller: AppBundle:ManageSurvey:delete }
   
question_list:
    path:     /question/list/{surveyid}
    defaults: { _controller: AppBundle:ManageQuestion:list }

question_create: 
    path:     /question/create/{surveyid}
    defaults: { _controller: AppBundle:ManageQuestion:create }

question_edit: 
    path:     /question/edit/{questionid}
    defaults: { _controller: AppBundle:ManageQuestion:edit }  

question_edit_option:
    path:     /question/edit_option/{questionid}
    defaults: { _controller: AppBundle:ManageQuestion:editOption } 
    
question_delete: 
    path:     /question/delete/{questionid}
    defaults: { _controller: AppBundle:ManageQuestion:delete }
    
answer_list:
    path:     /answer/list/{questionid}
    defaults: { _controller: AppBundle:ManageAnswer:list }

answer_create: 
    path:     /answer/create/{questionid}
    defaults: { _controller: AppBundle:ManageAnswer:create }

answer_edit: 
    path:     /answer/edit/{answerid}
    defaults: { _controller: AppBundle:ManageAnswer:edit }  
    
answer_delete: 
    path:     /answer/delete/{answerid}
    defaults: { _controller: AppBundle:ManageAnswer:delete }
    
instance_list:
    path:     /instance/list/{surveyid}
    defaults: { _controller: AppBundle:Instance:list }
    
instance_create:
    path:     /instance/create/{surveyid}
    defaults: { _controller: AppBundle:Instance:create }
    
instance_edit:
    path:     /instance/edit/{instanceid}
    defaults: { _controller: AppBundle:Instance:edit }
    
instance_delete:
    path:     /instance/delete/{instanceid}
    defaults: { _controller: AppBundle:Instance:delete }
    
response: 
    path:     /response/{code}
    defaults: { _controller: AppBundle:Response:viewSurvey }