AppBundle\Entity\Answer:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AnswerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        questionId:
            type: integer
    lifecycleCallbacks: {  }
